### ISSUE TITLE
Time Axis Markers missing on charts?

### ISSUE THREAD

**Issue by MoneroChan** [M5M400/supportxmr-gui#10]
Hello, 
The time axis markers appear to be missing from the line graph charts on the new GUI ?
 (9am, 10am, 11am, 12pm, etc... ) 

Time markers are really useful for troubleshooting when 
- miners disconnect,
- slow down due to heat/ temperature / times of day etc...
- general time based troubleshooting.
- without having to connect to each individual rig.

**Quickfix Solution**:
A static ( -1 -2 -3 -4,-5,-6,-7, 8hrs ago) line mark would suffice as a GIF/png below the chart as a quick fix, but the active one from the previous GUI wsa good.)  as that would help as a refernce point. or maybe add 7~8 lines on the background of the chart image as reference point.

Just a thought.

**Comment by Thunderosa** [comment]
Hi, a good suggestion, instead of static markers, I've added a tool tip to the miner chart that shows the local time and the hashrate. 

It'll be in the new release which is still a few days away, but you can check it and I'd like to hear your feedback on the demo version at https://www.monerooutreach.org/supportxmr/

**Comment by Thunderosa** [comment]
This has been built into the new release. I opted for points that hover to try to keep things streamlined and provide more information. Thanks for the suggestion!
