### ISSUE TITLE
Please add: Income 24h

### ISSUE THREAD

**Issue by tkoucinauci** [M5M400/supportxmr-gui#8]
I miss 24h income on supportxmr pool.

Please add it, i don't want to use excel tables every day :-) and note "xmr pending" every day on the same time.

txs!

**Comment by Thunderosa** [comment]
We're building in an income estimator in the next version, but it sounds like you want 24 hours of actual income?

If I'm understanding you right. Then the bad news is that it probably won't be possible. The good news is that I can work in something more like a trip odometer which might work well for you. So instead of a 24 hour window, it would be whenever you press the button to reset the counter to note your current pending amount and the timestamp.

I think this might be a helpful new feature. Thanks for bringing it up.

**Comment by tkoucinauci** [comment]
Yes, actual income :-)

If you can't build a database of each worker "xmr pending", and save that pending xmr for instance every hour to database, and than implement last 24h income based on that input, than ok... 

But, every improvement is good, so if you go to odometer, i will use it of course 👍

Thank you, for great pool!
